### ISSUE TITLE
Get original doc_id from dataset_view

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#128]
Is there any way to do this? For example, I want to print out a document that was misclassified.

**Comment by skystrife** [comment]
It doesn't store the `doc_id`s, but each `instance` has an `instance_id` (in field `id`). If the `dataset` for the corresponding `dataset_view` was constructed from an entire index, it should correspond to the `doc_id`. Otherwise, it indicates the position in the list of `doc_id`s from which it was constructed.

See: [`multiclass_dataset` ctor](https://github.com/meta-toolkit/meta/blob/master/include/meta/classify/multiclass_dataset.h#L36-L41) and corresponding [`dataset` ctor](https://github.com/meta-toolkit/meta/blob/master/include/meta/learn/dataset.h#L90-L104).

**Comment by smassung** [comment]
Ok, I see. So as long as the dataset was constructed from an entire corpus, the ids are equal. Thanks!
