### ISSUE TITLE
Training a german language model

### ISSUE THREAD

**Issue by leandermelms** [meta-toolkit/meta#145]
Hi, 

I've gone through the [documentation](https://meta-toolkit.org/language-models-tutorial.html) and I was wondering if it's possible to train a german language model.

Does MeTA currently support this?

**Comment by smassung** [comment]
Sure, if you generate an `.arpa` file, you can use it with MeTA's LM.

Just make sure that the tokenization is the same for 1) the input to KenLM to generate the `.arpa` file and 2) "test"/unseen German data with MeTA. Since KenLM assumes that the text input files are already tokenized, you should be able to use MeTA's ICU tokenizer to tokenize your data before feeding it to KenLM. By default `icu-tokenizer` assumes the input data encoding is UTF-8, but you can change that setting if necessary.

In general, using MeTA's LM trained on your own data would be the following procedure:
- create a `config.toml` with your desired tokenization settings
- tokenize your training data (e.g. `train.txt` -> `train.txt.tok`)
- run KenLM on `train.txt.tok` to generate `lm.arpa`
- use MeTA's LM to load `lm.arpa`
- in MeTA, use new data tokenized with the same `config.toml` as before and query your LM

**Comment by leandermelms** [comment]
Thank you for providing the detailed explanation how to proceed. I appreciate your efforts and will give it a shot!

**Comment by Joyeric2** [comment]
Dearest one
My name is Joy Eric how are you doing today and how about your health,hope you are fine and good.Any way after going through your profile in this site i became interested in you.I will like to have you as my good friend whom i will like to share my life experience with.Your sex, age, race nor distance does not matter to me rather what matters most in a relationship is the maturity,truth and honest that exist between friends.So i will like you to contact me back through my private mail address(joyeric688@gma!l.com )So that i can tell you more about my self and send you more photos of me.Yours Sincerely,

**Comment by skystrife** [comment]
I assume this is resolved? Closing for now.
