### ISSUE TITLE
crf tagger fails with SIGSEGV signal if faced with unknown word or word with typo

### ISSUE THREAD

**Issue by ivankarpey** [meta-toolkit/meta#171]
I assume the problem rely in the fact that in those case tagged word not inside a corpus. But failing in those case looks like something wrong for me. 

Based on the latest provided crf model this code cause problem for me:

```
std::vector<std::string> tokens{"Boby", "go", "to", "school", "every", "week"}; //Boby contains a typo. But could be any other word. 

std::string pathToModel = "/path/to/model";
crf crf1{pathToModel};
auto tg = crf1.make_tagger();
meta::sequence::sequence seq;

auto analyzer = meta::sequence::default_pos_analyzer();
analyzer.load(pathToModel);

std::for_each(sentence.begin(), sentence.end(), [&seq](std::string token) {
       seq.add_observation({meta::sequence::symbol_t{token}, meta::sequence::tag_t{"[UNK]"}});
});

analyzer.analyze(seq);
tg.tag(seq);

//... trying to print tagged results
```

**Comment by skystrife** [comment]
Admittedly this API could be better, but the problem is in the usage. [As described in the POS tagging tutorial](https://meta-toolkit.org/pos-tagging-tutorial.html#programmatically), you're missing the critical step

```cpp
const auto& ana = analyzer; // access the analyzer via const ref
                            // so that no new feature ids are generated
ana.analyze(seq);
```

Calling `analyze` on a non-`const` analyzer will allow it to generate new feature ids as is done during training. During testing, you want the `const` version of the function so that it ignores previously unseen features.

Let me know if that fixes the issue for you (I suspect it will).

**Comment by ivankarpey** [comment]
Indeed, accessing via const reference solving the problem. Looks like a magic for me (sorry, quite new in C++ after decade of coding other langs). Could you explain to me - how it's possible that the way we acessing object affect how logic executed?
