### ISSUE TITLE
can not compile ranking-experiment.cpp on macOS 10.12

### ISSUE THREAD

**Issue by suoigwg** [meta-toolkit/meta#179]
Major errors are 
```
ranking-experiment.cpp:45:45: error: 
      only virtual member functions can be marked 'override
```

```
ranking-experiment.cpp:127:29: error: 
      no viable conversion from
      'numerical_identifier<meta::doc_id_tag, [...]>' to
      'numerical_identifier<meta::query_id_tag, [...]>'
        eval.avg_p(ranking, (*query).id(), 1000);  // eval.avg_p stores the

```

Any help are appreciated!

**Comment by smassung** [comment]
Are you trying to make your own ranker? I can't give too much help on the first issue because I don't know what `ranking-experiment.cpp` is.

For the second error, it tells you what the problem is. You are trying to pass a document ID to something that expects a query ID (or a `uint64_t` to convert to a query ID...). I assume that the object `query` is a `meta::corpus::document`.

For both problems, you might find some answers here: https://meta-toolkit.org/search-tutorial.html

**Comment by suoigwg** [comment]
THANKS for the reply.
I was just doing what the setup tutorial said. I didn't changed anything.

发自我的 iPhone

**Comment by smassung** [comment]
There is no `ranking-experiment.cpp` in our codebase, so it looks like we can't help with your problem unless you give any additional information.
