### ISSUE TITLE
document scoring in memory optimizations

### ISSUE THREAD

**Issue by smassung** [meta-toolkit/meta#82]
Currently we use a `std::vector<double>` the size of `num_docs` to hold scores for documents being scored. While this is fine in general, large corpora (say with >100M documents) may take up too much memory.

We should investigate conditionally using `std::unordered_map<doc_id, double>` to hold scores for documents that actually *have* scores, unlike the current version which allocates memory for all documents even if they have no matching terms.

**Comment by skystrife** [comment]
So I was thinking about this earlier, and I think we can do something cute here.

There are basically two different approaches for doing the ranking when we get a query. One is "term-by-term" and one is "document-by-document".

In the "term-by-term" case, you fetch the postings list for a specific query term and then iterate through this postings list adding the scores to the appropriate accumulators. At the end, you extract the k-best list from the accumulators (either by sorting or being more clever). This is the method we currently use.

In the "document-by-document" case, you fetch *all* the postings lists for *all* of the query terms first, and keep these around. Then, you iterate over all the document ids and, for each one, you iterate in parallel across *all* of the fetched postings lists to score an entire document at once---you can do this efficiently by just keeping an index into each postings list since they should be in sorted order by document id. When you're done scoring a document, put it into a binary min-heap and ensure that the heap never has more than k documents in it. After you've iterated over all of the documents, simply output the top-k list by sorting the heap.

This second case has the nice property that it's easy to add a hook to the rankers for a document-specific "bias" score (or the "prior" probability of a document if you're thinking of the language model rankers): just set your initial score to that callback right when you start scoring that document.

The downside is that we have to hold all of the postings lists in memory for the duration of the ranking. Something tells me, though, that for most reasonable queries this would give a pretty nice trade-off. It should also be pretty fast (no hash table accesses). What do you think?

**Comment by smassung** [comment]
Oh, that's an interesting idea. I think in general that would work for the search engine component and have those nice properties you mentioned, but it might break down in something like *k*-NN, where our query is a (potentially) very large document. Obviously, the most common use case is the search engine. Maybe we could draft this and see how bad (if at all *k*-NN is).

Is this just an idea from random discussion or is this based on some paper/textbook?

**Comment by skystrife** [comment]
I forget my exact reference, but the Stanford IR book mentions this: http://nlp.stanford.edu/IR-book/ (section 6.3.3).

**Comment by skystrife** [comment]
Also relevant: http://www.savar.se/media/1181/space_optimizations_for_total_ranking.pdf

(Doug Cutting is the original author of Lucene.)

The main difference in architecture for us is that we load in the whole postings list at once, rather than streaming it in... So I think this way could potentially run us out of memory, like you mentioned.

**Comment by skystrife** [comment]
If we separate out the concerns of scoring from ranking, we could have a ranker for each strategy and switch between them as needed.

**Comment by skystrife** [comment]
Fixed with PR #83.
